apiVersion: v1
kind: Service
metadata:
  name: weatherapp-weather
  labels:
    app: weatherapp-weather
spec:
  selector:
    app.kubernetes.io/name: weatherapp-weather
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
